config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Hook up routes so localhost:3030 takes us to landing page
  root 'static_pages#index'
  resources :quotes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def new
    @quote = Quote.new
  end

   def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
     redirect_to root_path
   end

   private

   def quote_params
     params.require(:quote).permit(:saying, :author)
   end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
# Connect landing page to index action
  def index
    @quote = Quote.order("RANDOM()").first
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Literbug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <%= link_to 'Literbug', root_path, class: 'navbar-brand' %>
     
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>

    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


    
    <%= yield %>
  </body>
</html>

app/views/quotes/new.html.erb
<h1>Enter Your Quote Details</h1>
<%= simple_form_for @quote do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <%= f.input :book %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-10 offset-1 text-center">
    <h1><%= @quote.saying %></h1>
    <h2>- <%= @quote.author %></h2>
    <h3><%= @quote.book %></h3>
  </div>
</div>

<br />
<div class="row feature text-center">
  <div class="col-12 col-sm">
    <h3><%= link_to 'Add a Quote', new_quote_path, class: 'links' %></h3>
  </div>

  <div class="col-12 col-sm">
    <h3><%= link_to 'All Quotes', '#', class: 'links' %></h3>
  </div>

  <div class="col-12 col-sm">
    <h3><%= link_to 'Recommended Books', '#', class: 'links' %></h3>
  </div>

 </div>

app/views/static_pages/new.html.erb
<h1>Enter Your Quote Details</h1>